// GENERATED by tools/generate.py - do not edit.
window.DRIFT_DATA = {
 "generatedAt": "2026-09-13 09:41 UTC",
 "unit": 56,
 "layout": [
  {
   "x": 0.0,
   "y": 0.5,
   "r": 0,
   "rx": 0.0,
   "ry": 0.5,
   "half": "left"
  },
  {
   "x": 1.0,
   "y": 0.4,
   "r": 0,
   "rx": 1.0,
   "ry": 0.4,
   "half": "left"
  },
  {
   "x": 2.0,
   "y": 0.4,
   "r": 0,
   "rx": 2.0,
   "ry": 0.4,
   "half": "left"
  },
  {
   "x": 3.0,
   "y": 0.3,
   "r": 0,
   "rx": 3.0,
   "ry": 0.3,
   "half": "left"
  },
  {
   "x": 4.0,
   "y": 0.1,
   "r": 0,
   "rx": 4.0,
   "ry": 0.1,
   "half": "left"
  },
  {
   "x": 5.0,
   "y": 0.0,
   "r": 0,
   "rx": 5.0,
   "ry": 0.0,
   "half": "left"
  },
  {
   "x": 6.0,
   "y": 0.1,
   "r": 0,
   "rx": 6.0,
   "ry": 0.1,
   "half": "left"
  },
  {
   "x": 7.0,
   "y": 0.2,
   "r": 0,
   "rx": 7.0,
   "ry": 0.2,
   "half": "left"
  },
  {
   "x": 12.0,
   "y": 0.2,
   "r": 0,
   "rx": 12.0,
   "ry": 0.2,
   "half": "right"
  },
  {
   "x": 13.0,
   "y": 0.1,
   "r": 0,
   "rx": 13.0,
   "ry": 0.1,
   "half": "right"
  },
  {
   "x": 14.0,
   "y": 0.0,
   "r": 0,
   "rx": 14.0,
   "ry": 0.0,
   "half": "right"
  },
  {
   "x": 15.0,
   "y": 0.1,
   "r": 0,
   "rx": 15.0,
   "ry": 0.1,
   "half": "right"
  },
  {
   "x": 16.0,
   "y": 0.3,
   "r": 0,
   "rx": 16.0,
   "ry": 0.3,
   "half": "right"
  },
  {
   "x": 17.0,
   "y": 0.4,
   "r": 0,
   "rx": 17.0,
   "ry": 0.4,
   "half": "right"
  },
  {
   "x": 18.0,
   "y": 0.4,
   "r": 0,
   "rx": 18.0,
   "ry": 0.4,
   "half": "right"
  },
  {
   "x": 19.0,
   "y": 0.5,
   "r": 0,
   "rx": 19.0,
   "ry": 0.5,
   "half": "right"
  },
  {
   "x": 0.0,
   "y": 1.5,
   "r": 0,
   "rx": 0.0,
   "ry": 1.5,
   "half": "left"
  },
  {
   "x": 1.0,
   "y": 1.4,
   "r": 0,
   "rx": 1.0,
   "ry": 1.4,
   "half": "left"
  },
  {
   "x": 2.0,
   "y": 1.4,
   "r": 0,
   "rx": 2.0,
   "ry": 1.4,
   "half": "left"
  },
  {
   "x": 3.0,
   "y": 1.3,
   "r": 0,
   "rx": 3.0,
   "ry": 1.3,
   "half": "left"
  },
  {
   "x": 4.0,
   "y": 1.1,
   "r": 0,
   "rx": 4.0,
   "ry": 1.1,
   "half": "left"
  },
  {
   "x": 5.0,
   "y": 1.0,
   "r": 0,
   "rx": 5.0,
   "ry": 1.0,
   "half": "left"
  },
  {
   "x": 6.0,
   "y": 1.1,
   "r": 0,
   "rx": 6.0,
   "ry": 1.1,
   "half": "left"
  },
  {
   "x": 7.0,
   "y": 1.2,
   "r": 0,
   "rx": 7.0,
   "ry": 1.2,
   "half": "left"
  },
  {
   "x": 12.0,
   "y": 1.2,
   "r": 0,
   "rx": 12.0,
   "ry": 1.2,
   "half": "right"
  },
  {
   "x": 13.0,
   "y": 1.1,
   "r": 0,
   "rx": 13.0,
   "ry": 1.1,
   "half": "right"
  },
  {
   "x": 14.0,
   "y": 1.0,
   "r": 0,
   "rx": 14.0,
   "ry": 1.0,
   "half": "right"
  },
  {
   "x": 15.0,
   "y": 1.1,
   "r": 0,
   "rx": 15.0,
   "ry": 1.1,
   "half": "right"
  },
  {
   "x": 16.0,
   "y": 1.3,
   "r": 0,
   "rx": 16.0,
   "ry": 1.3,
   "half": "right"
  },
  {
   "x": 17.0,
   "y": 1.4,
   "r": 0,
   "rx": 17.0,
   "ry": 1.4,
   "half": "right"
  },
  {
   "x": 18.0,
   "y": 1.4,
   "r": 0,
   "rx": 18.0,
   "ry": 1.4,
   "half": "right"
  },
  {
   "x": 19.0,
   "y": 1.5,
   "r": 0,
   "rx": 19.0,
   "ry": 1.5,
   "half": "right"
  },
  {
   "x": 1.0,
   "y": 2.4,
   "r": 0,
   "rx": 1.0,
   "ry": 2.4,
   "half": "left"
  },
  {
   "x": 2.0,
   "y": 2.4,
   "r": 0,
   "rx": 2.0,
   "ry": 2.4,
   "half": "left"
  },
  {
   "x": 3.0,
   "y": 2.3,
   "r": 0,
   "rx": 3.0,
   "ry": 2.3,
   "half": "left"
  },
  {
   "x": 4.0,
   "y": 2.1,
   "r": 0,
   "rx": 4.0,
   "ry": 2.1,
   "half": "left"
  },
  {
   "x": 5.0,
   "y": 2.0,
   "r": 0,
   "rx": 5.0,
   "ry": 2.0,
   "half": "left"
  },
  {
   "x": 6.0,
   "y": 2.1,
   "r": 0,
   "rx": 6.0,
   "ry": 2.1,
   "half": "left"
  },
  {
   "x": 7.0,
   "y": 2.2,
   "r": 0,
   "rx": 7.0,
   "ry": 2.2,
   "half": "left"
  },
  {
   "x": 12.0,
   "y": 2.2,
   "r": 0,
   "rx": 12.0,
   "ry": 2.2,
   "half": "right"
  },
  {
   "x": 13.0,
   "y": 2.1,
   "r": 0,
   "rx": 13.0,
   "ry": 2.1,
   "half": "right"
  },
  {
   "x": 14.0,
   "y": 2.0,
   "r": 0,
   "rx": 14.0,
   "ry": 2.0,
   "half": "right"
  },
  {
   "x": 15.0,
   "y": 2.1,
   "r": 0,
   "rx": 15.0,
   "ry": 2.1,
   "half": "right"
  },
  {
   "x": 16.0,
   "y": 2.3,
   "r": 0,
   "rx": 16.0,
   "ry": 2.3,
   "half": "right"
  },
  {
   "x": 17.0,
   "y": 2.4,
   "r": 0,
   "rx": 17.0,
   "ry": 2.4,
   "half": "right"
  },
  {
   "x": 18.0,
   "y": 2.4,
   "r": 0,
   "rx": 18.0,
   "ry": 2.4,
   "half": "right"
  },
  {
   "x": 0.0,
   "y": 3.4,
   "r": 0,
   "rx": 0.0,
   "ry": 3.4,
   "half": "left"
  },
  {
   "x": 1.0,
   "y": 3.4,
   "r": 0,
   "rx": 1.0,
   "ry": 3.4,
   "half": "left"
  },
  {
   "x": 2.0,
   "y": 3.4,
   "r": 0,
   "rx": 2.0,
   "ry": 3.4,
   "half": "left"
  },
  {
   "x": 3.0,
   "y": 3.3,
   "r": 0,
   "rx": 3.0,
   "ry": 3.3,
   "half": "left"
  },
  {
   "x": 4.0,
   "y": 3.1,
   "r": 0,
   "rx": 4.0,
   "ry": 3.1,
   "half": "left"
  },
  {
   "x": 5.0,
   "y": 3.0,
   "r": 0,
   "rx": 5.0,
   "ry": 3.0,
   "half": "left"
  },
  {
   "x": 6.0,
   "y": 3.1,
   "r": 0,
   "rx": 6.0,
   "ry": 3.1,
   "half": "left"
  },
  {
   "x": 7.0,
   "y": 3.2,
   "r": 0,
   "rx": 7.0,
   "ry": 3.2,
   "half": "left"
  },
  {
   "x": 8.5,
   "y": 3.2,
   "r": 0,
   "rx": 8.5,
   "ry": 3.2,
   "half": "left"
  },
  {
   "x": 10.5,
   "y": 3.2,
   "r": 0,
   "rx": 10.5,
   "ry": 3.2,
   "half": "right"
  },
  {
   "x": 12.0,
   "y": 3.2,
   "r": 0,
   "rx": 12.0,
   "ry": 3.2,
   "half": "right"
  },
  {
   "x": 13.0,
   "y": 3.1,
   "r": 0,
   "rx": 13.0,
   "ry": 3.1,
   "half": "right"
  },
  {
   "x": 14.0,
   "y": 3.0,
   "r": 0,
   "rx": 14.0,
   "ry": 3.0,
   "half": "right"
  },
  {
   "x": 15.0,
   "y": 3.1,
   "r": 0,
   "rx": 15.0,
   "ry": 3.1,
   "half": "right"
  },
  {
   "x": 16.0,
   "y": 3.3,
   "r": 0,
   "rx": 16.0,
   "ry": 3.3,
   "half": "right"
  },
  {
   "x": 17.0,
   "y": 3.4,
   "r": 0,
   "rx": 17.0,
   "ry": 3.4,
   "half": "right"
  },
  {
   "x": 18.0,
   "y": 3.4,
   "r": 0,
   "rx": 18.0,
   "ry": 3.4,
   "half": "right"
  },
  {
   "x": 19.0,
   "y": 3.4,
   "r": 0,
   "rx": 19.0,
   "ry": 3.4,
   "half": "right"
  },
  {
   "x": 5.5,
   "y": 4.2,
   "r": 0,
   "rx": 5.5,
   "ry": 4.2,
   "half": "left"
  },
  {
   "x": 5.7,
   "y": 4.1,
   "r": 20,
   "rx": 5.8,
   "ry": 7.4,
   "half": "left"
  },
  {
   "x": 5.85,
   "y": 3.95,
   "r": 40,
   "rx": 5.8,
   "ry": 7.4,
   "half": "left"
  },
  {
   "x": 13.13,
   "y": 3.95,
   "r": -40,
   "rx": 14.15,
   "ry": 7.4,
   "half": "right"
  },
  {
   "x": 13.29,
   "y": 4.1,
   "r": -20,
   "rx": 14.15,
   "ry": 7.4,
   "half": "right"
  },
  {
   "x": 13.5,
   "y": 4.2,
   "r": 0,
   "rx": 13.5,
   "ry": 4.2,
   "half": "right"
  }
 ],
 "layers": {
  "base": [
   {
    "raw": "&kp ESC",
    "en": "Esc",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Escape",
    "mods": []
   },
   {
    "raw": "&kp PG_UP",
    "en": "PgUp",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "PageUp",
    "mods": []
   },
   {
    "raw": "&kp GRAVE",
    "en": "`",
    "en_shift": "~",
    "th": "_",
    "th_shift": "%",
    "code": "Backquote",
    "mods": []
   },
   {
    "raw": "&kp N1",
    "en": "1",
    "en_shift": "!",
    "th": "ๅ",
    "th_shift": "+",
    "code": "Digit1",
    "mods": []
   },
   {
    "raw": "&kp N2",
    "en": "2",
    "en_shift": "@",
    "th": "/",
    "th_shift": "๑",
    "code": "Digit2",
    "mods": []
   },
   {
    "raw": "&kp N3",
    "en": "3",
    "en_shift": "#",
    "th": "-",
    "th_shift": "๒",
    "code": "Digit3",
    "mods": []
   },
   {
    "raw": "&kp N4",
    "en": "4",
    "en_shift": "$",
    "th": "ภ",
    "th_shift": "๓",
    "code": "Digit4",
    "mods": []
   },
   {
    "raw": "&kp N5",
    "en": "5",
    "en_shift": "%",
    "th": "ถ",
    "th_shift": "๔",
    "code": "Digit5",
    "mods": []
   },
   {
    "raw": "&kp N6",
    "en": "6",
    "en_shift": "^",
    "th": "ุ",
    "th_shift": "ู",
    "code": "Digit6",
    "mods": []
   },
   {
    "raw": "&kp N7",
    "en": "7",
    "en_shift": "&",
    "th": "ึ",
    "th_shift": "฿",
    "code": "Digit7",
    "mods": []
   },
   {
    "raw": "&kp N8",
    "en": "8",
    "en_shift": "*",
    "th": "ค",
    "th_shift": "๕",
    "code": "Digit8",
    "mods": []
   },
   {
    "raw": "&kp N9",
    "en": "9",
    "en_shift": "(",
    "th": "ต",
    "th_shift": "๖",
    "code": "Digit9",
    "mods": []
   },
   {
    "raw": "&kp N0",
    "en": "0",
    "en_shift": ")",
    "th": "จ",
    "th_shift": "๗",
    "code": "Digit0",
    "mods": []
   },
   {
    "raw": "&kp MINUS",
    "en": "-",
    "en_shift": "_",
    "th": "ข",
    "th_shift": "๘",
    "code": "Minus",
    "mods": []
   },
   {
    "raw": "&kp EQUAL",
    "en": "=",
    "en_shift": "+",
    "th": "ช",
    "th_shift": "๙",
    "code": "Equal",
    "mods": []
   },
   {
    "raw": "&kp BSPC",
    "en": "⌫",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Backspace",
    "mods": []
   },
   {
    "raw": "&kp LG(C)",
    "en": "⌘C",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "KeyC",
    "mods": [
     "Meta"
    ]
   },
   {
    "raw": "&kp PG_DN",
    "en": "PgDn",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "PageDown",
    "mods": []
   },
   {
    "raw": "&kp TAB",
    "en": "Tab",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Tab",
    "mods": []
   },
   {
    "raw": "&kp Q",
    "en": "Q",
    "en_shift": "",
    "th": "ๆ",
    "th_shift": "๐",
    "code": "KeyQ",
    "mods": []
   },
   {
    "raw": "&kp W",
    "en": "W",
    "en_shift": "",
    "th": "ไ",
    "th_shift": "\"",
    "code": "KeyW",
    "mods": []
   },
   {
    "raw": "&kp E",
    "en": "E",
    "en_shift": "",
    "th": "ำ",
    "th_shift": "ฎ",
    "code": "KeyE",
    "mods": []
   },
   {
    "raw": "&kp R",
    "en": "R",
    "en_shift": "",
    "th": "พ",
    "th_shift": "ฑ",
    "code": "KeyR",
    "mods": []
   },
   {
    "raw": "&kp T",
    "en": "T",
    "en_shift": "",
    "th": "ะ",
    "th_shift": "ธ",
    "code": "KeyT",
    "mods": []
   },
   {
    "raw": "&kp Y",
    "en": "Y",
    "en_shift": "",
    "th": "ั",
    "th_shift": "ํ",
    "code": "KeyY",
    "mods": []
   },
   {
    "raw": "&kp U",
    "en": "U",
    "en_shift": "",
    "th": "ี",
    "th_shift": "๊",
    "code": "KeyU",
    "mods": []
   },
   {
    "raw": "&kp I",
    "en": "I",
    "en_shift": "",
    "th": "ร",
    "th_shift": "ณ",
    "code": "KeyI",
    "mods": []
   },
   {
    "raw": "&kp O",
    "en": "O",
    "en_shift": "",
    "th": "น",
    "th_shift": "ฯ",
    "code": "KeyO",
    "mods": []
   },
   {
    "raw": "&kp P",
    "en": "P",
    "en_shift": "",
    "th": "ย",
    "th_shift": "ญ",
    "code": "KeyP",
    "mods": []
   },
   {
    "raw": "&kp LBKT",
    "en": "[",
    "en_shift": "{",
    "th": "บ",
    "th_shift": "ฐ",
    "code": "BracketLeft",
    "mods": []
   },
   {
    "raw": "&kp RBKT",
    "en": "]",
    "en_shift": "}",
    "th": "ล",
    "th_shift": ",",
    "code": "BracketRight",
    "mods": []
   },
   {
    "raw": "&kp BSLH",
    "en": "\\",
    "en_shift": "|",
    "th": "ฃ",
    "th_shift": "ฅ",
    "code": "Backslash",
    "mods": []
   },
   {
    "raw": "&kp LSHFT",
    "en": "⇧",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ShiftLeft",
    "mods": []
   },
   {
    "raw": "&kp CAPS",
    "en": "Caps",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "CapsLock",
    "mods": []
   },
   {
    "raw": "&kp A",
    "en": "A",
    "en_shift": "",
    "th": "ฟ",
    "th_shift": "ฤ",
    "code": "KeyA",
    "mods": []
   },
   {
    "raw": "&kp S",
    "en": "S",
    "en_shift": "",
    "th": "ห",
    "th_shift": "ฆ",
    "code": "KeyS",
    "mods": []
   },
   {
    "raw": "&kp D",
    "en": "D",
    "en_shift": "",
    "th": "ก",
    "th_shift": "ฏ",
    "code": "KeyD",
    "mods": []
   },
   {
    "raw": "&kp F",
    "en": "F",
    "en_shift": "",
    "th": "ด",
    "th_shift": "โ",
    "code": "KeyF",
    "mods": []
   },
   {
    "raw": "&kp G",
    "en": "G",
    "en_shift": "",
    "th": "เ",
    "th_shift": "ฌ",
    "code": "KeyG",
    "mods": []
   },
   {
    "raw": "&kp H",
    "en": "H",
    "en_shift": "",
    "th": "้",
    "th_shift": "็",
    "code": "KeyH",
    "mods": []
   },
   {
    "raw": "&kp J",
    "en": "J",
    "en_shift": "",
    "th": "่",
    "th_shift": "๋",
    "code": "KeyJ",
    "mods": []
   },
   {
    "raw": "&kp K",
    "en": "K",
    "en_shift": "",
    "th": "า",
    "th_shift": "ษ",
    "code": "KeyK",
    "mods": []
   },
   {
    "raw": "&kp L",
    "en": "L",
    "en_shift": "",
    "th": "ส",
    "th_shift": "ศ",
    "code": "KeyL",
    "mods": []
   },
   {
    "raw": "&kp SEMI",
    "en": ";",
    "en_shift": ":",
    "th": "ว",
    "th_shift": "ซ",
    "code": "Semicolon",
    "mods": []
   },
   {
    "raw": "&kp SQT",
    "en": "'",
    "en_shift": "\"",
    "th": "ง",
    "th_shift": ".",
    "code": "Quote",
    "mods": []
   },
   {
    "raw": "&kp ENTER",
    "en": "⏎",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Enter",
    "mods": []
   },
   {
    "raw": "&kp LG(V)",
    "en": "⌘V",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "KeyV",
    "mods": [
     "Meta"
    ]
   },
   {
    "raw": "&kp LCTRL",
    "en": "⌃",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ControlLeft",
    "mods": []
   },
   {
    "raw": "&kp LALT",
    "en": "⌥",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "AltLeft",
    "mods": []
   },
   {
    "raw": "&kp Z",
    "en": "Z",
    "en_shift": "",
    "th": "ผ",
    "th_shift": "(",
    "code": "KeyZ",
    "mods": []
   },
   {
    "raw": "&kp X",
    "en": "X",
    "en_shift": "",
    "th": "ป",
    "th_shift": ")",
    "code": "KeyX",
    "mods": []
   },
   {
    "raw": "&kp C",
    "en": "C",
    "en_shift": "",
    "th": "แ",
    "th_shift": "ฉ",
    "code": "KeyC",
    "mods": []
   },
   {
    "raw": "&kp V",
    "en": "V",
    "en_shift": "",
    "th": "อ",
    "th_shift": "ฮ",
    "code": "KeyV",
    "mods": []
   },
   {
    "raw": "&kp B",
    "en": "B",
    "en_shift": "",
    "th": "ิ",
    "th_shift": "ฺ",
    "code": "KeyB",
    "mods": []
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp N",
    "en": "N",
    "en_shift": "",
    "th": "ื",
    "th_shift": "์",
    "code": "KeyN",
    "mods": []
   },
   {
    "raw": "&kp M",
    "en": "M",
    "en_shift": "",
    "th": "ท",
    "th_shift": "?",
    "code": "KeyM",
    "mods": []
   },
   {
    "raw": "&kp COMMA",
    "en": ",",
    "en_shift": "<",
    "th": "ม",
    "th_shift": "ฒ",
    "code": "Comma",
    "mods": []
   },
   {
    "raw": "&kp DOT",
    "en": ".",
    "en_shift": ">",
    "th": "ใ",
    "th_shift": "ฬ",
    "code": "Period",
    "mods": []
   },
   {
    "raw": "&kp FSLH",
    "en": "/",
    "en_shift": "?",
    "th": "ฝ",
    "th_shift": "ฦ",
    "code": "Slash",
    "mods": []
   },
   {
    "raw": "&kp RSHFT",
    "en": "⇧",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ShiftRight",
    "mods": []
   },
   {
    "raw": "&kp RGUI",
    "en": "⌘",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "MetaRight",
    "mods": []
   },
   {
    "raw": "&kp DEL",
    "en": "⌦",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Delete",
    "mods": []
   },
   {
    "raw": "&kp LGUI",
    "en": "⌘",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "MetaLeft",
    "mods": []
   },
   {
    "raw": "&kp SPACE",
    "en": "␣",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Space",
    "mods": []
   },
   {
    "raw": "&mo LOWER",
    "en": "lower",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&mo RAISE",
    "en": "raise",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp SPACE",
    "en": "␣",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Space",
    "mods": []
   },
   {
    "raw": "&kp BSPC",
    "en": "⌫",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Backspace",
    "mods": []
   }
  ],
  "lower": [
   {
    "raw": "&bootloader",
    "en": "Boot",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp LG(LS(N4))",
    "en": "⌘⇧4",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Digit4",
    "mods": [
     "Meta",
     "Shift"
    ]
   },
   {
    "raw": "&kp GRAVE",
    "en": "`",
    "en_shift": "~",
    "th": "_",
    "th_shift": "%",
    "code": "Backquote",
    "mods": []
   },
   {
    "raw": "&kp F1",
    "en": "F1",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F1",
    "mods": []
   },
   {
    "raw": "&kp F2",
    "en": "F2",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F2",
    "mods": []
   },
   {
    "raw": "&kp F3",
    "en": "F3",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F3",
    "mods": []
   },
   {
    "raw": "&kp F4",
    "en": "F4",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F4",
    "mods": []
   },
   {
    "raw": "&kp F5",
    "en": "F5",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F5",
    "mods": []
   },
   {
    "raw": "&kp F6",
    "en": "F6",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F6",
    "mods": []
   },
   {
    "raw": "&kp F7",
    "en": "F7",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F7",
    "mods": []
   },
   {
    "raw": "&kp F8",
    "en": "F8",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F8",
    "mods": []
   },
   {
    "raw": "&kp F9",
    "en": "F9",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F9",
    "mods": []
   },
   {
    "raw": "&kp F10",
    "en": "F10",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F10",
    "mods": []
   },
   {
    "raw": "&kp F11",
    "en": "F11",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F11",
    "mods": []
   },
   {
    "raw": "&kp F12",
    "en": "F12",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F12",
    "mods": []
   },
   {
    "raw": "&kp DEL",
    "en": "⌦",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Delete",
    "mods": []
   },
   {
    "raw": "&kp LG(LS(N5))",
    "en": "⌘⇧5",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Digit5",
    "mods": [
     "Meta",
     "Shift"
    ]
   },
   {
    "raw": "&kp LG(LS(N3))",
    "en": "⌘⇧3",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Digit3",
    "mods": [
     "Meta",
     "Shift"
    ]
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp LG(LEFT)",
    "en": "⌘←",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowLeft",
    "mods": [
     "Meta"
    ]
   },
   {
    "raw": "&kp LG(RIGHT)",
    "en": "⌘→",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowRight",
    "mods": [
     "Meta"
    ]
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp LC(SPACE)",
    "en": "⌃␣",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Space",
    "mods": [
     "Control"
    ]
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp UP",
    "en": "↑",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowUp",
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp LEFT",
    "en": "←",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowLeft",
    "mods": []
   },
   {
    "raw": "&kp DOWN",
    "en": "↓",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowDown",
    "mods": []
   },
   {
    "raw": "&kp RIGHT",
    "en": "→",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowRight",
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp DEL",
    "en": "⌦",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Delete",
    "mods": []
   }
  ],
  "raise": [
   {
    "raw": "&bt BT_CLR",
    "en": "BT clr",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_CLR_ALL",
    "en": "BT clr all",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_SEL 0",
    "en": "BT1",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_SEL 1",
    "en": "BT2",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_SEL 2",
    "en": "BT3",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_SEL 3",
    "en": "BT4",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_SEL 4",
    "en": "BT5",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_BRI_DN",
    "en": "☀−",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_BRI_UP",
    "en": "☀+",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_PREV",
    "en": "⏮",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_PP",
    "en": "⏯",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_NEXT",
    "en": "⏭",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bootloader",
    "en": "Boot",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp LG(SPACE)",
    "en": "⌘␣",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Space",
    "mods": [
     "Meta"
    ]
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&mkp MCLK",
    "en": "click M",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&msc SCRL_DOWN",
    "en": "scroll ↓",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&mkp RCLK",
    "en": "click R",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&mkp LCLK",
    "en": "click L",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&mmv MOVE_UP",
    "en": "mouse ↑",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&mmv MOVE_LEFT",
    "en": "mouse ←",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&mmv MOVE_DOWN",
    "en": "mouse ↓",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&mmv MOVE_RIGHT",
    "en": "mouse →",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   }
  ],
  "adjust": [
   {
    "raw": "&bootloader",
    "en": "Boot",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&sys_reset",
    "en": "Reset",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_SEL 0",
    "en": "BT1",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_SEL 1",
    "en": "BT2",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_SEL 2",
    "en": "BT3",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_SEL 3",
    "en": "BT4",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bt BT_SEL 4",
    "en": "BT5",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&out OUT_USB",
    "en": "USB",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&out OUT_BLE",
    "en": "BLE",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&out OUT_TOG",
    "en": "USB/BLE",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&sys_reset",
    "en": "Reset",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&bootloader",
    "en": "Boot",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": []
   }
  ]
 },
 "test": {
  "slots": [
   "KeyA",
   "KeyB",
   "KeyC",
   "KeyD",
   "KeyE",
   "KeyF",
   "KeyG",
   "KeyH",
   "KeyI",
   "KeyJ",
   "KeyK",
   "KeyL",
   "KeyM",
   "KeyN",
   "KeyO",
   "KeyP",
   "KeyQ",
   "KeyR",
   "KeyS",
   "KeyT",
   "KeyU",
   "KeyV",
   "KeyW",
   "KeyX",
   "KeyY",
   "KeyZ",
   "Digit1",
   "Digit2",
   "Digit3",
   "Digit4",
   "Digit5",
   "Digit6",
   "Digit7",
   "Digit8",
   "Digit9",
   "Digit0",
   "F13",
   "F14",
   "F15",
   "F16",
   "F17",
   "F18",
   "F19",
   "F20",
   "F21",
   "F22",
   "F23",
   "F24",
   "Backquote",
   "Minus",
   "Equal",
   "BracketLeft",
   "BracketRight",
   "Backslash",
   "Semicolon",
   "Quote",
   "Comma",
   "Period",
   "Slash",
   "Tab",
   "Space",
   "Backspace",
   "Delete",
   "Enter",
   "PageUp",
   "PageDown",
   "Home",
   "End",
   "Insert",
   "ArrowUp"
  ],
  "encoders": [
   {
    "label": "encoder ซ้าย",
    "half": "left",
    "cw": "ArrowDown",
    "ccw": "ArrowLeft"
   },
   {
    "label": "encoder ขวา",
    "half": "right",
    "cw": "ArrowRight",
    "ccw": "Escape"
   }
  ]
 }
};
