// GENERATED by tools/generate.py - do not edit.
window.DRIFT_DATA = {
 "source": "d1ec5391",
 "unit": 56,
 "layout": [
  {
   "x": 0.0,
   "y": 0.5,
   "r": 0,
   "rx": 0.0,
   "ry": 0.5,
   "half": "left"
  },
  {
   "x": 1.0,
   "y": 0.4,
   "r": 0,
   "rx": 1.0,
   "ry": 0.4,
   "half": "left"
  },
  {
   "x": 2.0,
   "y": 0.4,
   "r": 0,
   "rx": 2.0,
   "ry": 0.4,
   "half": "left"
  },
  {
   "x": 3.0,
   "y": 0.3,
   "r": 0,
   "rx": 3.0,
   "ry": 0.3,
   "half": "left"
  },
  {
   "x": 4.0,
   "y": 0.1,
   "r": 0,
   "rx": 4.0,
   "ry": 0.1,
   "half": "left"
  },
  {
   "x": 5.0,
   "y": 0.0,
   "r": 0,
   "rx": 5.0,
   "ry": 0.0,
   "half": "left"
  },
  {
   "x": 6.0,
   "y": 0.1,
   "r": 0,
   "rx": 6.0,
   "ry": 0.1,
   "half": "left"
  },
  {
   "x": 7.0,
   "y": 0.2,
   "r": 0,
   "rx": 7.0,
   "ry": 0.2,
   "half": "left"
  },
  {
   "x": 12.0,
   "y": 0.2,
   "r": 0,
   "rx": 12.0,
   "ry": 0.2,
   "half": "right"
  },
  {
   "x": 13.0,
   "y": 0.1,
   "r": 0,
   "rx": 13.0,
   "ry": 0.1,
   "half": "right"
  },
  {
   "x": 14.0,
   "y": 0.0,
   "r": 0,
   "rx": 14.0,
   "ry": 0.0,
   "half": "right"
  },
  {
   "x": 15.0,
   "y": 0.1,
   "r": 0,
   "rx": 15.0,
   "ry": 0.1,
   "half": "right"
  },
  {
   "x": 16.0,
   "y": 0.3,
   "r": 0,
   "rx": 16.0,
   "ry": 0.3,
   "half": "right"
  },
  {
   "x": 17.0,
   "y": 0.4,
   "r": 0,
   "rx": 17.0,
   "ry": 0.4,
   "half": "right"
  },
  {
   "x": 18.0,
   "y": 0.4,
   "r": 0,
   "rx": 18.0,
   "ry": 0.4,
   "half": "right"
  },
  {
   "x": 19.0,
   "y": 0.5,
   "r": 0,
   "rx": 19.0,
   "ry": 0.5,
   "half": "right"
  },
  {
   "x": 0.0,
   "y": 1.5,
   "r": 0,
   "rx": 0.0,
   "ry": 1.5,
   "half": "left"
  },
  {
   "x": 1.0,
   "y": 1.4,
   "r": 0,
   "rx": 1.0,
   "ry": 1.4,
   "half": "left"
  },
  {
   "x": 2.0,
   "y": 1.4,
   "r": 0,
   "rx": 2.0,
   "ry": 1.4,
   "half": "left"
  },
  {
   "x": 3.0,
   "y": 1.3,
   "r": 0,
   "rx": 3.0,
   "ry": 1.3,
   "half": "left"
  },
  {
   "x": 4.0,
   "y": 1.1,
   "r": 0,
   "rx": 4.0,
   "ry": 1.1,
   "half": "left"
  },
  {
   "x": 5.0,
   "y": 1.0,
   "r": 0,
   "rx": 5.0,
   "ry": 1.0,
   "half": "left"
  },
  {
   "x": 6.0,
   "y": 1.1,
   "r": 0,
   "rx": 6.0,
   "ry": 1.1,
   "half": "left"
  },
  {
   "x": 7.0,
   "y": 1.2,
   "r": 0,
   "rx": 7.0,
   "ry": 1.2,
   "half": "left"
  },
  {
   "x": 12.0,
   "y": 1.2,
   "r": 0,
   "rx": 12.0,
   "ry": 1.2,
   "half": "right"
  },
  {
   "x": 13.0,
   "y": 1.1,
   "r": 0,
   "rx": 13.0,
   "ry": 1.1,
   "half": "right"
  },
  {
   "x": 14.0,
   "y": 1.0,
   "r": 0,
   "rx": 14.0,
   "ry": 1.0,
   "half": "right"
  },
  {
   "x": 15.0,
   "y": 1.1,
   "r": 0,
   "rx": 15.0,
   "ry": 1.1,
   "half": "right"
  },
  {
   "x": 16.0,
   "y": 1.3,
   "r": 0,
   "rx": 16.0,
   "ry": 1.3,
   "half": "right"
  },
  {
   "x": 17.0,
   "y": 1.4,
   "r": 0,
   "rx": 17.0,
   "ry": 1.4,
   "half": "right"
  },
  {
   "x": 18.0,
   "y": 1.4,
   "r": 0,
   "rx": 18.0,
   "ry": 1.4,
   "half": "right"
  },
  {
   "x": 19.0,
   "y": 1.5,
   "r": 0,
   "rx": 19.0,
   "ry": 1.5,
   "half": "right"
  },
  {
   "x": 1.0,
   "y": 2.4,
   "r": 0,
   "rx": 1.0,
   "ry": 2.4,
   "half": "left"
  },
  {
   "x": 2.0,
   "y": 2.4,
   "r": 0,
   "rx": 2.0,
   "ry": 2.4,
   "half": "left"
  },
  {
   "x": 3.0,
   "y": 2.3,
   "r": 0,
   "rx": 3.0,
   "ry": 2.3,
   "half": "left"
  },
  {
   "x": 4.0,
   "y": 2.1,
   "r": 0,
   "rx": 4.0,
   "ry": 2.1,
   "half": "left"
  },
  {
   "x": 5.0,
   "y": 2.0,
   "r": 0,
   "rx": 5.0,
   "ry": 2.0,
   "half": "left"
  },
  {
   "x": 6.0,
   "y": 2.1,
   "r": 0,
   "rx": 6.0,
   "ry": 2.1,
   "half": "left"
  },
  {
   "x": 7.0,
   "y": 2.2,
   "r": 0,
   "rx": 7.0,
   "ry": 2.2,
   "half": "left"
  },
  {
   "x": 12.0,
   "y": 2.2,
   "r": 0,
   "rx": 12.0,
   "ry": 2.2,
   "half": "right"
  },
  {
   "x": 13.0,
   "y": 2.1,
   "r": 0,
   "rx": 13.0,
   "ry": 2.1,
   "half": "right"
  },
  {
   "x": 14.0,
   "y": 2.0,
   "r": 0,
   "rx": 14.0,
   "ry": 2.0,
   "half": "right"
  },
  {
   "x": 15.0,
   "y": 2.1,
   "r": 0,
   "rx": 15.0,
   "ry": 2.1,
   "half": "right"
  },
  {
   "x": 16.0,
   "y": 2.3,
   "r": 0,
   "rx": 16.0,
   "ry": 2.3,
   "half": "right"
  },
  {
   "x": 17.0,
   "y": 2.4,
   "r": 0,
   "rx": 17.0,
   "ry": 2.4,
   "half": "right"
  },
  {
   "x": 18.0,
   "y": 2.4,
   "r": 0,
   "rx": 18.0,
   "ry": 2.4,
   "half": "right"
  },
  {
   "x": 0.0,
   "y": 3.4,
   "r": 0,
   "rx": 0.0,
   "ry": 3.4,
   "half": "left"
  },
  {
   "x": 1.0,
   "y": 3.4,
   "r": 0,
   "rx": 1.0,
   "ry": 3.4,
   "half": "left"
  },
  {
   "x": 2.0,
   "y": 3.4,
   "r": 0,
   "rx": 2.0,
   "ry": 3.4,
   "half": "left"
  },
  {
   "x": 3.0,
   "y": 3.3,
   "r": 0,
   "rx": 3.0,
   "ry": 3.3,
   "half": "left"
  },
  {
   "x": 4.0,
   "y": 3.1,
   "r": 0,
   "rx": 4.0,
   "ry": 3.1,
   "half": "left"
  },
  {
   "x": 5.0,
   "y": 3.0,
   "r": 0,
   "rx": 5.0,
   "ry": 3.0,
   "half": "left"
  },
  {
   "x": 6.0,
   "y": 3.1,
   "r": 0,
   "rx": 6.0,
   "ry": 3.1,
   "half": "left"
  },
  {
   "x": 7.0,
   "y": 3.2,
   "r": 0,
   "rx": 7.0,
   "ry": 3.2,
   "half": "left"
  },
  {
   "x": 8.5,
   "y": 3.2,
   "r": 0,
   "rx": 8.5,
   "ry": 3.2,
   "half": "left"
  },
  {
   "x": 10.5,
   "y": 3.2,
   "r": 0,
   "rx": 10.5,
   "ry": 3.2,
   "half": "right"
  },
  {
   "x": 12.0,
   "y": 3.2,
   "r": 0,
   "rx": 12.0,
   "ry": 3.2,
   "half": "right"
  },
  {
   "x": 13.0,
   "y": 3.1,
   "r": 0,
   "rx": 13.0,
   "ry": 3.1,
   "half": "right"
  },
  {
   "x": 14.0,
   "y": 3.0,
   "r": 0,
   "rx": 14.0,
   "ry": 3.0,
   "half": "right"
  },
  {
   "x": 15.0,
   "y": 3.1,
   "r": 0,
   "rx": 15.0,
   "ry": 3.1,
   "half": "right"
  },
  {
   "x": 16.0,
   "y": 3.3,
   "r": 0,
   "rx": 16.0,
   "ry": 3.3,
   "half": "right"
  },
  {
   "x": 17.0,
   "y": 3.4,
   "r": 0,
   "rx": 17.0,
   "ry": 3.4,
   "half": "right"
  },
  {
   "x": 18.0,
   "y": 3.4,
   "r": 0,
   "rx": 18.0,
   "ry": 3.4,
   "half": "right"
  },
  {
   "x": 19.0,
   "y": 3.4,
   "r": 0,
   "rx": 19.0,
   "ry": 3.4,
   "half": "right"
  },
  {
   "x": 5.5,
   "y": 4.2,
   "r": 0,
   "rx": 5.5,
   "ry": 4.2,
   "half": "left"
  },
  {
   "x": 5.7,
   "y": 4.1,
   "r": 20,
   "rx": 5.8,
   "ry": 7.4,
   "half": "left"
  },
  {
   "x": 5.85,
   "y": 3.95,
   "r": 40,
   "rx": 5.8,
   "ry": 7.4,
   "half": "left"
  },
  {
   "x": 13.13,
   "y": 3.95,
   "r": -40,
   "rx": 14.15,
   "ry": 7.4,
   "half": "right"
  },
  {
   "x": 13.29,
   "y": 4.1,
   "r": -20,
   "rx": 14.15,
   "ry": 7.4,
   "half": "right"
  },
  {
   "x": 13.5,
   "y": 4.2,
   "r": 0,
   "rx": 13.5,
   "ry": 4.2,
   "half": "right"
  }
 ],
 "layer_order": [
  "base",
  "game",
  "nav",
  "mouse",
  "adjust"
 ],
 "conditional": {
  "if": [
   "nav",
   "mouse"
  ],
  "then": "adjust"
 },
 "layers": {
  "base": [
   {
    "raw": "&kp ESC",
    "en": "Esc",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Escape",
    "mods": [],
    "note": "Escape"
   },
   {
    "raw": "&kp PG_UP",
    "en": "PgUp",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "PageUp",
    "mods": [],
    "note": "เลื่อนขึ้นหนึ่งหน้าจอ"
   },
   {
    "raw": "&kp GRAVE",
    "en": "`",
    "en_shift": "~",
    "th": "_",
    "th_shift": "%",
    "code": "Backquote",
    "mods": [],
    "note": "` กับ ~ (ไทย: _ กับ %)"
   },
   {
    "raw": "&kp N1",
    "en": "1",
    "en_shift": "!",
    "th": "ๅ",
    "th_shift": "+",
    "code": "Digit1",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp N2",
    "en": "2",
    "en_shift": "@",
    "th": "/",
    "th_shift": "๑",
    "code": "Digit2",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp N3",
    "en": "3",
    "en_shift": "#",
    "th": "-",
    "th_shift": "๒",
    "code": "Digit3",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp N4",
    "en": "4",
    "en_shift": "$",
    "th": "ภ",
    "th_shift": "๓",
    "code": "Digit4",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp N5",
    "en": "5",
    "en_shift": "%",
    "th": "ถ",
    "th_shift": "๔",
    "code": "Digit5",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp N6",
    "en": "6",
    "en_shift": "^",
    "th": "ุ",
    "th_shift": "ู",
    "code": "Digit6",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp N7",
    "en": "7",
    "en_shift": "&",
    "th": "ึ",
    "th_shift": "฿",
    "code": "Digit7",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp N8",
    "en": "8",
    "en_shift": "*",
    "th": "ค",
    "th_shift": "๕",
    "code": "Digit8",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp N9",
    "en": "9",
    "en_shift": "(",
    "th": "ต",
    "th_shift": "๖",
    "code": "Digit9",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp N0",
    "en": "0",
    "en_shift": ")",
    "th": "จ",
    "th_shift": "๗",
    "code": "Digit0",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp MINUS",
    "en": "-",
    "en_shift": "_",
    "th": "ข",
    "th_shift": "๘",
    "code": "Minus",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp EQUAL",
    "en": "=",
    "en_shift": "+",
    "th": "ช",
    "th_shift": "๙",
    "code": "Equal",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp BSPC",
    "en": "⌫",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Backspace",
    "mods": [],
    "note": "ปุ่ม delete ปกติของ Mac (⌫) ลบตัวอักษรทางซ้าย"
   },
   {
    "raw": "&kp LG(C)",
    "en": "⌘C",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "KeyC",
    "mods": [
     "Meta"
    ],
    "note": "⌘C คัดลอก — บน Mac ต้องเป็น ⌘ ไม่ใช่ Ctrl"
   },
   {
    "raw": "&kp PG_DN",
    "en": "PgDn",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "PageDown",
    "mods": [],
    "note": "เลื่อนลงหนึ่งหน้าจอ"
   },
   {
    "raw": "&kp TAB",
    "en": "Tab",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Tab",
    "mods": [],
    "note": "Tab"
   },
   {
    "raw": "&kp Q",
    "en": "Q",
    "en_shift": "",
    "th": "ๆ",
    "th_shift": "๐",
    "code": "KeyQ",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp W",
    "en": "W",
    "en_shift": "",
    "th": "ไ",
    "th_shift": "\"",
    "code": "KeyW",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp E",
    "en": "E",
    "en_shift": "",
    "th": "ำ",
    "th_shift": "ฎ",
    "code": "KeyE",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp R",
    "en": "R",
    "en_shift": "",
    "th": "พ",
    "th_shift": "ฑ",
    "code": "KeyR",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp T",
    "en": "T",
    "en_shift": "",
    "th": "ะ",
    "th_shift": "ธ",
    "code": "KeyT",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp Y",
    "en": "Y",
    "en_shift": "",
    "th": "ั",
    "th_shift": "ํ",
    "code": "KeyY",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp U",
    "en": "U",
    "en_shift": "",
    "th": "ี",
    "th_shift": "๊",
    "code": "KeyU",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp I",
    "en": "I",
    "en_shift": "",
    "th": "ร",
    "th_shift": "ณ",
    "code": "KeyI",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp O",
    "en": "O",
    "en_shift": "",
    "th": "น",
    "th_shift": "ฯ",
    "code": "KeyO",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp P",
    "en": "P",
    "en_shift": "",
    "th": "ย",
    "th_shift": "ญ",
    "code": "KeyP",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp LBKT",
    "en": "[",
    "en_shift": "{",
    "th": "บ",
    "th_shift": "ฐ",
    "code": "BracketLeft",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp RBKT",
    "en": "]",
    "en_shift": "}",
    "th": "ล",
    "th_shift": ",",
    "code": "BracketRight",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp BSLH",
    "en": "\\",
    "en_shift": "|",
    "th": "ฃ",
    "th_shift": "ฅ",
    "code": "Backslash",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp LSHFT",
    "en": "⇧",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ShiftLeft",
    "mods": [],
    "note": "⇧ Shift"
   },
   {
    "raw": "&kp LC(SPACE)",
    "en": "⌃␣",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Space",
    "mods": [
     "Control"
    ],
    "note": "⌃Space สลับ input source ไทย ↔ อังกฤษ — อยู่บน keycap ที่สลักว่า Caps (Caps Lock จริงย้ายไป layer adjust ช่องเดียวกัน) · ในโหมดคู่มือปุ่มนี้ไม่สว่าง เพราะ macOS กินไปก่อนถึง browser"
   },
   {
    "raw": "&kp A",
    "en": "A",
    "en_shift": "",
    "th": "ฟ",
    "th_shift": "ฤ",
    "code": "KeyA",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp S",
    "en": "S",
    "en_shift": "",
    "th": "ห",
    "th_shift": "ฆ",
    "code": "KeyS",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp D",
    "en": "D",
    "en_shift": "",
    "th": "ก",
    "th_shift": "ฏ",
    "code": "KeyD",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F",
    "en": "F",
    "en_shift": "",
    "th": "ด",
    "th_shift": "โ",
    "code": "KeyF",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp G",
    "en": "G",
    "en_shift": "",
    "th": "เ",
    "th_shift": "ฌ",
    "code": "KeyG",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp H",
    "en": "H",
    "en_shift": "",
    "th": "้",
    "th_shift": "็",
    "code": "KeyH",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp J",
    "en": "J",
    "en_shift": "",
    "th": "่",
    "th_shift": "๋",
    "code": "KeyJ",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp K",
    "en": "K",
    "en_shift": "",
    "th": "า",
    "th_shift": "ษ",
    "code": "KeyK",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp L",
    "en": "L",
    "en_shift": "",
    "th": "ส",
    "th_shift": "ศ",
    "code": "KeyL",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp SEMI",
    "en": ";",
    "en_shift": ":",
    "th": "ว",
    "th_shift": "ซ",
    "code": "Semicolon",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp SQT",
    "en": "'",
    "en_shift": "\"",
    "th": "ง",
    "th_shift": ".",
    "code": "Quote",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp ENTER",
    "en": "⏎",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Enter",
    "mods": [],
    "note": "Return / Enter"
   },
   {
    "raw": "&kp LG(V)",
    "en": "⌘V",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "KeyV",
    "mods": [
     "Meta"
    ],
    "note": "⌘V วาง"
   },
   {
    "raw": "&kp LCTRL",
    "en": "⌃",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ControlLeft",
    "mods": [],
    "note": "⌃ Control"
   },
   {
    "raw": "&kp LALT",
    "en": "⌥",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "AltLeft",
    "mods": [],
    "note": "⌥ Option"
   },
   {
    "raw": "&kp Z",
    "en": "Z",
    "en_shift": "",
    "th": "ผ",
    "th_shift": "(",
    "code": "KeyZ",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp X",
    "en": "X",
    "en_shift": "",
    "th": "ป",
    "th_shift": ")",
    "code": "KeyX",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp C",
    "en": "C",
    "en_shift": "",
    "th": "แ",
    "th_shift": "ฉ",
    "code": "KeyC",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp V",
    "en": "V",
    "en_shift": "",
    "th": "อ",
    "th_shift": "ฮ",
    "code": "KeyV",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp B",
    "en": "B",
    "en_shift": "",
    "th": "ิ",
    "th_shift": "ฺ",
    "code": "KeyB",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ปิด/เปิดเสียง — ช่องนี้คือการกด encoder ซ้ายลงไป ไม่ใช่ปุ่มธรรมดา"
   },
   {
    "raw": "&kp C_PP",
    "en": "⏯",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เล่น / หยุดชั่วคราว — ช่องตรงกลางบอร์ดคือการกด encoder ขวาลงไป"
   },
   {
    "raw": "&kp N",
    "en": "N",
    "en_shift": "",
    "th": "ื",
    "th_shift": "์",
    "code": "KeyN",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp M",
    "en": "M",
    "en_shift": "",
    "th": "ท",
    "th_shift": "?",
    "code": "KeyM",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp COMMA",
    "en": ",",
    "en_shift": "<",
    "th": "ม",
    "th_shift": "ฒ",
    "code": "Comma",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp DOT",
    "en": ".",
    "en_shift": ">",
    "th": "ใ",
    "th_shift": "ฬ",
    "code": "Period",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp FSLH",
    "en": "/",
    "en_shift": "?",
    "th": "ฝ",
    "th_shift": "ฦ",
    "code": "Slash",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp RSHFT",
    "en": "⇧",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ShiftRight",
    "mods": [],
    "note": "⇧ Shift ตัวขวา"
   },
   {
    "raw": "&kp RGUI",
    "en": "⌘",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "MetaRight",
    "mods": [],
    "note": "⌘ Command ตัวขวา — ใช้ ⌘-click ในโหมด mouse ได้ เพราะ thumb ⌘ ซ้ายกลายเป็นคลิกขวา"
   },
   {
    "raw": "&kp DEL",
    "en": "⌦",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Delete",
    "mods": [],
    "note": "forward delete (⌦) ลบตัวอักษรทางขวา — บนคีย์บอร์ด Apple ต้องกด Fn+Delete"
   },
   {
    "raw": "&kp LGUI",
    "en": "⌘",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "MetaLeft",
    "mods": [],
    "note": "⌘ Command"
   },
   {
    "raw": "&kp SPACE",
    "en": "␣",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Space",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&mo NAV",
    "en": "nav",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "กดค้างเพื่อเข้า layer nav ปล่อยแล้วกลับ layer เดิม — กดพร้อมกับ mouse จะเข้า layer adjust"
   },
   {
    "raw": "&mo MOUSE",
    "en": "mouse",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "กดค้างเพื่อเข้า layer mouse ปล่อยแล้วกลับ layer เดิม — กดพร้อมกับ nav จะเข้า layer adjust"
   },
   {
    "raw": "&kp SPACE",
    "en": "␣",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Space",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp BSPC",
    "en": "⌫",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Backspace",
    "mods": [],
    "note": "ปุ่ม delete ปกติของ Mac (⌫) ลบตัวอักษรทางซ้าย"
   }
  ],
  "game": [
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kpws W",
    "en": "W",
    "en_shift": "",
    "th": "ไ",
    "th_shift": "\"",
    "code": "KeyW",
    "mods": [],
    "note": "ปุ่มธรรมดาสำหรับ host แต่ถ้ากด W กับ S ค้างพร้อมกัน ตัวที่กดทีหลังชนะ (last-input-priority สำหรับเกม จาก module ของ Timception) — มีเฉพาะโหมด game บน base เป็นปุ่มธรรมดา"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kpad A",
    "en": "A",
    "en_shift": "",
    "th": "ฟ",
    "th_shift": "ฤ",
    "code": "KeyA",
    "mods": [],
    "note": "ปุ่มธรรมดาสำหรับ host แต่ถ้ากด A กับ D ค้างพร้อมกัน ตัวที่กดทีหลังชนะ (last-input-priority สำหรับเกม จาก module ของ Timception) — มีเฉพาะโหมด game บน base เป็นปุ่มธรรมดา"
   },
   {
    "raw": "&kpws S",
    "en": "S",
    "en_shift": "",
    "th": "ห",
    "th_shift": "ฆ",
    "code": "KeyS",
    "mods": [],
    "note": "ปุ่มธรรมดาสำหรับ host แต่ถ้ากด W กับ S ค้างพร้อมกัน ตัวที่กดทีหลังชนะ (last-input-priority สำหรับเกม จาก module ของ Timception) — มีเฉพาะโหมด game บน base เป็นปุ่มธรรมดา"
   },
   {
    "raw": "&kpad D",
    "en": "D",
    "en_shift": "",
    "th": "ก",
    "th_shift": "ฏ",
    "code": "KeyD",
    "mods": [],
    "note": "ปุ่มธรรมดาสำหรับ host แต่ถ้ากด A กับ D ค้างพร้อมกัน ตัวที่กดทีหลังชนะ (last-input-priority สำหรับเกม จาก module ของ Timception) — มีเฉพาะโหมด game บน base เป็นปุ่มธรรมดา"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ปิด/เปิดเสียง — ช่องนี้คือการกด encoder ซ้ายลงไป ไม่ใช่ปุ่มธรรมดา"
   },
   {
    "raw": "&kp C_PP",
    "en": "⏯",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เล่น / หยุดชั่วคราว — ช่องตรงกลางบอร์ดคือการกด encoder ขวาลงไป"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp LALT",
    "en": "⌥",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "AltLeft",
    "mods": [],
    "note": "⌥ Option"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   }
  ],
  "nav": [
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp LG(LS(N4))",
    "en": "⌘⇧4",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Digit4",
    "mods": [
     "Meta",
     "Shift"
    ],
    "note": "⌘⇧4 ถ่ายภาพหน้าจอแบบลากเลือกพื้นที่"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp F1",
    "en": "F1",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F1",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F2",
    "en": "F2",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F2",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F3",
    "en": "F3",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F3",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F4",
    "en": "F4",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F4",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F5",
    "en": "F5",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F5",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F6",
    "en": "F6",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F6",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F7",
    "en": "F7",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F7",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F8",
    "en": "F8",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F8",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F9",
    "en": "F9",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F9",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F10",
    "en": "F10",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F10",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F11",
    "en": "F11",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F11",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp F12",
    "en": "F12",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "F12",
    "mods": [],
    "note": ""
   },
   {
    "raw": "&kp DEL",
    "en": "⌦",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Delete",
    "mods": [],
    "note": "forward delete (⌦) ลบตัวอักษรทางขวา — บนคีย์บอร์ด Apple ต้องกด Fn+Delete"
   },
   {
    "raw": "&kp LG(LS(N5))",
    "en": "⌘⇧5",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Digit5",
    "mods": [
     "Meta",
     "Shift"
    ],
    "note": "⌘⇧5 เปิดแถบเครื่องมือถ่ายภาพ/อัดวิดีโอหน้าจอ"
   },
   {
    "raw": "&kp LG(LS(N3))",
    "en": "⌘⇧3",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Digit3",
    "mods": [
     "Meta",
     "Shift"
    ],
    "note": "⌘⇧3 ถ่ายภาพหน้าจอทั้งจอ เซฟลง Desktop ทันที"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp LG(GRAVE)",
    "en": "⌘`",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Backquote",
    "mods": [
     "Meta"
    ],
    "note": "⌘` หน้าต่างถัดไปของ app เดียวกัน"
   },
   {
    "raw": "&kp LC(UP)",
    "en": "⌃↑",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowUp",
    "mods": [
     "Control"
    ],
    "note": "⌃↑ Mission Control — เห็นทุกหน้าต่างและทุก Space"
   },
   {
    "raw": "&kp LG(TAB)",
    "en": "⌘Tab",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Tab",
    "mods": [
     "Meta"
    ],
    "note": "⌘Tab สลับไป app ที่ใช้ล่าสุด (กดค้างจะเปิดตัวเลือก app) · ในโหมดคู่มือปุ่มนี้ไม่สว่างเพราะ macOS กินไปก่อน"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp HOME",
    "en": "Home",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Home",
    "mods": [],
    "note": "ไปต้นเอกสาร/ต้นหน้า (ใน editor ส่วนใหญ่ = ต้นบรรทัด)"
   },
   {
    "raw": "&kp PG_DN",
    "en": "PgDn",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "PageDown",
    "mods": [],
    "note": "เลื่อนลงหนึ่งหน้าจอ"
   },
   {
    "raw": "&kp PG_UP",
    "en": "PgUp",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "PageUp",
    "mods": [],
    "note": "เลื่อนขึ้นหนึ่งหน้าจอ"
   },
   {
    "raw": "&kp END",
    "en": "End",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "End",
    "mods": [],
    "note": "ไปท้ายเอกสาร/ท้ายหน้า (ใน editor ส่วนใหญ่ = ท้ายบรรทัด)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&caps_word",
    "en": "CapsW",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "Caps Word — ตัวอักษรถัดไปเป็นตัวใหญ่ทั้งหมด แล้วปิดเองเมื่อเจอ space หรือเครื่องหมาย (ขีดล่าง ตัวเลข ⌫ ไม่ตัด) เหมาะกับ CONSTANT_NAME ในโค้ด"
   },
   {
    "raw": "&kp LC(LEFT)",
    "en": "⌃←",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowLeft",
    "mods": [
     "Control"
    ],
    "note": "⌃← ไป Space ทางซ้าย"
   },
   {
    "raw": "&kp LC(DOWN)",
    "en": "⌃↓",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowDown",
    "mods": [
     "Control"
    ],
    "note": "⌃↓ App Exposé — หน้าต่างทั้งหมดของ app ที่ใช้อยู่"
   },
   {
    "raw": "&kp LC(RIGHT)",
    "en": "⌃→",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowRight",
    "mods": [
     "Control"
    ],
    "note": "⌃→ ไป Space ทางขวา"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp LEFT",
    "en": "←",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowLeft",
    "mods": [],
    "note": "← กด ⌥ ค้าง = ถอยทีละคำ · ⌘ ค้าง = ต้นบรรทัด · ⇧ ค้าง = เลือกข้อความ · ⌃⌥ ค้าง = tile หน้าต่างซ้าย"
   },
   {
    "raw": "&kp DOWN",
    "en": "↓",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowDown",
    "mods": [],
    "note": "↓ กด ⌥ ค้าง = ท้ายย่อหน้า · ⌘ ค้าง = ท้ายเอกสาร · ⌃⌥ ค้าง = tile หน้าต่างล่าง"
   },
   {
    "raw": "&kp UP",
    "en": "↑",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowUp",
    "mods": [],
    "note": "↑ กด ⌥ ค้าง = ต้นย่อหน้า · ⌘ ค้าง = ต้นเอกสาร · ⌃⌥ ค้าง = tile หน้าต่างบน"
   },
   {
    "raw": "&kp RIGHT",
    "en": "→",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "ArrowRight",
    "mods": [],
    "note": "→ กด ⌥ ค้าง = ไปทีละคำ · ⌘ ค้าง = ท้ายบรรทัด · ⇧ ค้าง = เลือกข้อความ · ⌃⌥ ค้าง = tile หน้าต่างขวา"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ปิด/เปิดเสียง — ช่องนี้คือการกด encoder ซ้ายลงไป ไม่ใช่ปุ่มธรรมดา"
   },
   {
    "raw": "&kp C_PP",
    "en": "⏯",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เล่น / หยุดชั่วคราว — ช่องตรงกลางบอร์ดคือการกด encoder ขวาลงไป"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp DEL",
    "en": "⌦",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "Delete",
    "mods": [],
    "note": "forward delete (⌦) ลบตัวอักษรทางขวา — บนคีย์บอร์ด Apple ต้องกด Fn+Delete"
   }
  ],
  "mouse": [
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&msc MOVE_X(-10)",
    "en": "scroll ←",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เลื่อนหน้าไปทางซ้าย เหมือนหมุนล้อเมาส์ (ความเร็ว 10)"
   },
   {
    "raw": "&msc MOVE_Y(-10)",
    "en": "scroll ↓",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เลื่อนหน้าลง เหมือนหมุนล้อเมาส์ (ความเร็ว 10)"
   },
   {
    "raw": "&msc MOVE_Y(10)",
    "en": "scroll ↑",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เลื่อนหน้าขึ้น เหมือนหมุนล้อเมาส์ (ความเร็ว 10)"
   },
   {
    "raw": "&msc MOVE_X(10)",
    "en": "scroll →",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เลื่อนหน้าไปทางขวา เหมือนหมุนล้อเมาส์ (ความเร็ว 10)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&mkp MCLK",
    "en": "click M",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "คลิกล้อกลางของเมาส์"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&mmv MOVE_LEFT",
    "en": "mouse ←",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ขยับเคอร์เซอร์เมาส์ไปทางซ้าย — แตะสั้นขยับนิดเดียว กดค้างจะเร่งความเร็วขึ้น"
   },
   {
    "raw": "&mmv MOVE_DOWN",
    "en": "mouse ↓",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ขยับเคอร์เซอร์เมาส์ลง — แตะสั้นขยับนิดเดียว กดค้างจะเร่งความเร็วขึ้น"
   },
   {
    "raw": "&mmv MOVE_UP",
    "en": "mouse ↑",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ขยับเคอร์เซอร์เมาส์ขึ้น — แตะสั้นขยับนิดเดียว กดค้างจะเร่งความเร็วขึ้น"
   },
   {
    "raw": "&mmv MOVE_RIGHT",
    "en": "mouse →",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ขยับเคอร์เซอร์เมาส์ไปทางขวา — แตะสั้นขยับนิดเดียว กดค้างจะเร่งความเร็วขึ้น"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ปิด/เปิดเสียง — ช่องนี้คือการกด encoder ซ้ายลงไป ไม่ใช่ปุ่มธรรมดา"
   },
   {
    "raw": "&kp C_PP",
    "en": "⏯",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เล่น / หยุดชั่วคราว — ช่องตรงกลางบอร์ดคือการกด encoder ขวาลงไป"
   },
   {
    "raw": "&mkp MB4",
    "en": "back",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ปุ่มเมาส์ 4 = ย้อนกลับ (Back) ใน browser และ Finder"
   },
   {
    "raw": "&mkp MB5",
    "en": "fwd",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ปุ่มเมาส์ 5 = ไปข้างหน้า (Forward) ใน browser และ Finder"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&mkp RCLK",
    "en": "click R",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "คลิกขวาของเมาส์"
   },
   {
    "raw": "&mkp LCLK",
    "en": "click L",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "คลิกซ้ายของเมาส์ — กดค้างแล้วขยับ = ลาก"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   }
  ],
  "adjust": [
   {
    "raw": "&bootloader",
    "en": "Boot",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เข้าโหมด bootloader ของเครื่องที่กด — drive NICENANO จะโผล่ขึ้นมาให้ลากไฟล์ .uf2 ลงไป"
   },
   {
    "raw": "&sys_reset",
    "en": "Reset",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "รีสตาร์ทบอร์ด เหมือนถอดแบตเสียบใหม่ ไม่ได้เข้า bootloader"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&bt BT_SEL 0",
    "en": "BT1",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "สลับไปใช้ Bluetooth profile ที่ 1 — dongle จำเครื่องได้ 5 เครื่องแยกกัน สลับเครื่องโดยไม่ต้องจับคู่ใหม่"
   },
   {
    "raw": "&bt BT_SEL 1",
    "en": "BT2",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "สลับไปใช้ Bluetooth profile ที่ 2 — dongle จำเครื่องได้ 5 เครื่องแยกกัน สลับเครื่องโดยไม่ต้องจับคู่ใหม่"
   },
   {
    "raw": "&bt BT_SEL 2",
    "en": "BT3",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "สลับไปใช้ Bluetooth profile ที่ 3 — dongle จำเครื่องได้ 5 เครื่องแยกกัน สลับเครื่องโดยไม่ต้องจับคู่ใหม่"
   },
   {
    "raw": "&bt BT_SEL 3",
    "en": "BT4",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "สลับไปใช้ Bluetooth profile ที่ 4 — dongle จำเครื่องได้ 5 เครื่องแยกกัน สลับเครื่องโดยไม่ต้องจับคู่ใหม่"
   },
   {
    "raw": "&bt BT_SEL 4",
    "en": "BT5",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "สลับไปใช้ Bluetooth profile ที่ 5 — dongle จำเครื่องได้ 5 เครื่องแยกกัน สลับเครื่องโดยไม่ต้องจับคู่ใหม่"
   },
   {
    "raw": "&kp C_BRI_DN",
    "en": "☀−",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ลดความสว่างหน้าจอ"
   },
   {
    "raw": "&kp C_BRI_UP",
    "en": "☀+",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เพิ่มความสว่างหน้าจอ"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp C_PREV",
    "en": "⏮",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เพลง/วิดีโอ ก่อนหน้า"
   },
   {
    "raw": "&kp C_PP",
    "en": "⏯",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เล่น / หยุดชั่วคราว — ช่องตรงกลางบอร์ดคือการกด encoder ขวาลงไป"
   },
   {
    "raw": "&kp C_NEXT",
    "en": "⏭",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เพลง/วิดีโอ ถัดไป"
   },
   {
    "raw": "&bootloader",
    "en": "Boot",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เข้าโหมด bootloader ของเครื่องที่กด — drive NICENANO จะโผล่ขึ้นมาให้ลากไฟล์ .uf2 ลงไป"
   },
   {
    "raw": "&bt BT_CLR",
    "en": "BT clr",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ลบการจับคู่ของ Bluetooth profile ที่ใช้อยู่ตอนนี้ ใช้ตอนจับคู่ใหม่ไม่ติด"
   },
   {
    "raw": "&bt BT_CLR_ALL",
    "en": "BT clr all",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ลบการจับคู่ของทุก profile พร้อมกัน"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&out OUT_USB",
    "en": "USB",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "บังคับส่งสัญญาณออกทางสาย USB อย่างเดียว"
   },
   {
    "raw": "&out OUT_BLE",
    "en": "BLE",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "บังคับส่งสัญญาณออกทาง Bluetooth อย่างเดียว"
   },
   {
    "raw": "&out OUT_TOG",
    "en": "USB/BLE",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "สลับไปมาระหว่าง USB กับ Bluetooth"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp CAPS",
    "en": "Caps",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "CapsLock",
    "mods": [],
    "note": "Caps Lock จริง — บน base ช่องนี้เป็น ⌃Space สลับภาษา ถ้าอยากล็อกตัวใหญ่จริงๆ มากดที่นี่"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&tog GAME",
    "en": "game ⏻",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เปิด/ปิดโหมด game ค้างไว้ — กดครั้งเดียวเปิด กดชุดเดียวกันอีกครั้งปิด จอ OLED บน dock โชว์ชื่อ game ตอนที่เปิดอยู่"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp LG(LC(Q))",
    "en": "⌘⌃Q",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": "KeyQ",
    "mods": [
     "Control",
     "Meta"
    ],
    "note": "⌃⌘Q ล็อกหน้าจอ"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&kp C_MUTE",
    "en": "🔇",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "ปิด/เปิดเสียง — ช่องนี้คือการกด encoder ซ้ายลงไป ไม่ใช่ปุ่มธรรมดา"
   },
   {
    "raw": "&kp C_PP",
    "en": "⏯",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "เล่น / หยุดชั่วคราว — ช่องตรงกลางบอร์ดคือการกด encoder ขวาลงไป"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   },
   {
    "raw": "&trans",
    "en": "▽",
    "en_shift": "",
    "th": "",
    "th_shift": "",
    "code": null,
    "mods": [],
    "note": "โปร่งใส — ปุ่มนี้ไม่ได้ทำอะไรของตัวเอง ใช้ค่าจาก layer ที่อยู่ข้างล่าง (ปกติคือ base)"
   }
  ]
 },
 "encoders": [
  {
   "half": "left",
   "label": "encoder ซ้าย",
   "cw": "เลื่อนหน้าขึ้น",
   "ccw": "เลื่อนหน้าลง"
  },
  {
   "half": "right",
   "label": "encoder ขวา",
   "cw": "เพิ่มเสียง",
   "ccw": "ลดเสียง"
  }
 ],
 "layers_encoders": {
  "base": [
   {
    "half": "left",
    "label": "encoder ซ้าย",
    "cw": "เลื่อนหน้าขึ้น",
    "ccw": "เลื่อนหน้าลง"
   },
   {
    "half": "right",
    "label": "encoder ขวา",
    "cw": "เพิ่มเสียง",
    "ccw": "ลดเสียง"
   }
  ],
  "game": [
   {
    "half": "left",
    "label": "encoder ซ้าย",
    "cw": "เลื่อนหน้าขึ้น",
    "ccw": "เลื่อนหน้าลง"
   },
   {
    "half": "right",
    "label": "encoder ขวา",
    "cw": "เพิ่มเสียง",
    "ccw": "ลดเสียง"
   }
  ],
  "nav": [
   {
    "half": "left",
    "label": "encoder ซ้าย",
    "cw": "เลื่อนหน้าไปทางขวา",
    "ccw": "เลื่อนหน้าไปทางซ้าย"
   },
   {
    "half": "right",
    "label": "encoder ขวา",
    "cw": "tab ถัดไป (⌃Tab)",
    "ccw": "tab ก่อนหน้า (⌃⇧Tab)"
   }
  ],
  "mouse": [
   {
    "half": "left",
    "label": "encoder ซ้าย",
    "cw": "เลื่อนหน้าขึ้น",
    "ccw": "เลื่อนหน้าลง"
   },
   {
    "half": "right",
    "label": "encoder ขวา",
    "cw": "เพิ่มเสียง",
    "ccw": "ลดเสียง"
   }
  ],
  "adjust": [
   {
    "half": "left",
    "label": "encoder ซ้าย",
    "cw": "เลื่อนหน้าขึ้น",
    "ccw": "เลื่อนหน้าลง"
   },
   {
    "half": "right",
    "label": "encoder ขวา",
    "cw": "เพิ่มเสียง",
    "ccw": "ลดเสียง"
   }
  ]
 },
 "test": {
  "slots": [
   "KeyA",
   "KeyB",
   "KeyC",
   "KeyD",
   "KeyE",
   "KeyF",
   "KeyG",
   "KeyH",
   "KeyI",
   "KeyJ",
   "KeyK",
   "KeyL",
   "KeyM",
   "KeyN",
   "KeyO",
   "KeyP",
   "KeyQ",
   "KeyR",
   "KeyS",
   "KeyT",
   "KeyU",
   "KeyV",
   "KeyW",
   "KeyX",
   "KeyY",
   "KeyZ",
   "Digit1",
   "Digit2",
   "Digit3",
   "Digit4",
   "Digit5",
   "Digit6",
   "Digit7",
   "Digit8",
   "Digit9",
   "Digit0",
   "F13",
   "F14",
   "F15",
   "F16",
   "F17",
   "F18",
   "F19",
   "F20",
   "F21",
   "F22",
   "F23",
   "F24",
   "Backquote",
   "Minus",
   "Equal",
   "BracketLeft",
   "BracketRight",
   "Backslash",
   "Semicolon",
   "Quote",
   "Comma",
   "Period",
   "Slash",
   "Tab",
   "Space",
   "Backspace",
   "Delete",
   "Enter",
   "PageUp",
   "PageDown",
   "Home",
   "End",
   "Insert",
   "ArrowUp"
  ],
  "encoders": [
   {
    "label": "encoder ซ้าย",
    "half": "left",
    "cw": "ArrowDown",
    "ccw": "ArrowLeft"
   },
   {
    "label": "encoder ขวา",
    "half": "right",
    "cw": "ArrowRight",
    "ccw": "Escape"
   }
  ]
 }
};
